### ISSUE TITLE
Lein check error

### ISSUE THREAD

**Issue by ptaoussanis** [mpenet/grease#1]
Hi Max, `lein check` seems to be having a problem with the grease dep:

```
Compiling 1 source files to /Users/ptaoussanis/Projects/taoensso/target/classes
Compiling namespace taoensso.rig.environment
Exception in thread "main" java.lang.ClassNotFoundException: cc.qbits.grease.io.FastByteArrayInputStream
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
```

**Comment by ptaoussanis** [comment]
Seems to only happen with a particular (AOT) project. It's a large project with a _lot_ of dependencies. Will try do some debugging later.

**Comment by mpenet** [comment]
can you show me your java and javac versions?

**Comment by ptaoussanis** [comment]
```
java version "1.7.0_04"
Java(TM) SE Runtime Environment (build 1.7.0_04-b21)
Java HotSpot(TM) 64-Bit Server VM (build 23.0-b21, mixed mode)

javac 1.7.0_04
```

**Comment by ptaoussanis** [comment]
I suspect this'll probably be easier to debug from my end, will try take a look later - just juggling a few things today. Figured I'd bring it up in case you had an idea off-hand.

**Comment by mpenet** [comment]
Sure, thanks a lot. I suspect just putting the java6 flags on the root project would fix this, but if you can get to understand what is going on that would be great.

**Comment by ptaoussanis** [comment]
Hey, sorry for never following up on this. Any developments on your end in the interim? Do you actually have any idea what in the codebase makes the JVM6 target necessary? Could it maybe be avoided?

Honestly haven't had any time to look into this, but just pinging to mention that I'm still open to integrating with Nippy if we can ensure there's no AOT issues.

Hope all's well otherwise! Cheers! :-)

**Comment by mpenet** [comment]
Hi Peter,

I was on vacation (it ends today sadly), so I didnt really have time to dig
into this. But I will try to have another look at it next week if the giant
pile of work I have pending allows me to.

Cheers

**Comment by ptaoussanis** [comment]
Ahh, vacation... I think I'm a couple years overdue ;-) Hope yours was good? Zero (!) stress or urgency about this - was just pinging so you didn't think I'd forgotten.

**Comment by mpenet** [comment]
It was very good (<3 Greece) and also long overdue, thanks!
